/*
 * SSROBOT_HAL.h
 *
 *  Created on: Sep 1, 2024
 *      Author: stevenketiah
 */

#ifndef INC_SSROBOT_HAL_H_
#define INC_SSROBOT_HAL_H_

#define TIME_LSB 0.01

typedef enum{
	SSROBOT_1_256STEP = 0,
	SSROBOT_1_128STEP,
	SSROBOT_1_64STEP,
	SSROBOT_1_32STEP,
	SSROBOT_1_16STEP,
	SSROBOT_EIGHTHSTEP,
	SSROBOT_QUARTERSTEP,
	SSROBOT_HALFSTEP,
	SSROBOT_FULLSTEP
}SSROBOT_MICROSTEP;


typedef enum {
	SSROBOT_OK = 0x00U,
	SSROBOT_ERROR = 0x01U

}SSROBOT_Status;

typedef enum {
	STEPPER_CALIBRATE = 			0x00,
	STEPPER_HOMING = 				0x01,
	STEPPER_MOVE_TO_POSITION = 		0x02,
	STEPPER_PATH_PLANNING = 		0X03,

	STEPPER_SET_MICROSTEP = 		0x10,
	STEPPER_SET_CURRENT = 			0x11,
	STEPPER_SET_SPEED = 			0x12,
	STEPPER_SET_OPERATION_MODE = 	0x13,

	STEPPER_WAITING = 				0xFF

}STEPPER_STATE;

typedef enum {
	CONTROLLER_INIT = 				0x00,
	CONTROLLER_WAITING= 			0x01,

	CONTROLLER_UART_ENABLE = 		0x02,
	CONTROLLER_UART_DISABLE=		0x03,

	CONTROLLER_MH=					0x04,	//Move Home
	CONTROLLER_MTP=					0x05,	//Move To Position
	CONTROLLER_PP= 					0x06	//Path Planning

}SSROBOT_CONTROLLER_STATE;

typedef enum {
	ALL_JOINTS= 0xFF,
	CONTROLLER= 0x00,
	JOINT_1 = 	0x01,
	JOINT_2 = 	0x02,
	JOINT_3 = 	0x03,
	JOINT_4 = 	0x04,
	JOINT_5 = 	0x05,
	JOINT_6 = 	0x06,
	GRIPPER = 	0x07

}JOINT_ADDRESS;


#endif /* INC_SSROBOT_HAL_H_ */
